### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by 37Gin** [37Gin/furima-36755#22]
## フリマアプリのURL
https://furima-36755.herokuapp.com/

## Basic認証のIDとパスワード
ID: terao
パスワード: 2684

## 出品者用のメールアドレスとパスワード
mail: sample@mail.com
pass: test00
（ニックネームはTEST1）

## 購入者用のメールアドレスとパスワード
mail: sample2@mail.com
pass: test00
（ニックネームはTEST2）

**Comment by snkw-works** [comment]
@37Gin さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **商品一覧ページにて、左上から、出品された日時が新しい順に表示されるよう修正しましょう**
現在は左上から古い順に表示されています。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by 37Gin** [comment]
確認ありがとうございます。
上記の内容について修正し反映されていることを確認したため、再度確認をお願いいたします。

**Comment by mo1015** [comment]
フリマアプリ達成要件分の開発お疲れ様でした！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/6852

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/132786675-3c5ab793-aa16-4ed9-aeb6-1bcc7f66c2ae.png)
